### ISSUE TITLE
MabiPacker-2.0alpha Selecting File Name Errors

### ISSUE THREAD

**Issue by shaggyze** [logue/MabiPack#6]
![chrome_2019-06-22_09-18-45](https://user-images.githubusercontent.com/6075285/59966269-de952180-94ce-11e9-8ee3-b788093a90c7.png)

Error when clicking folder/broswe for Pack > Output file name:

`   at MS.Internal.AppModel.ShellUtil.GetShellItemForPath(String path)
   at Microsoft.Win32.FileDialog.PrepareVistaDialog(IFileDialog dialog)
   at Microsoft.Win32.FileDialog.RunVistaDialog(IntPtr hwndOwner)
   at Microsoft.Win32.FileDialog.RunDialog(IntPtr hwndOwner)
   at Microsoft.Win32.CommonDialog.ShowDialog()
   at MabiPacker.View.MainWindow.Button_SetPackFileName_Click(Object sender, RoutedEventArgs e) in D:\Documents\Visual Studio 2017\Projects\MabiPack\MabiPacker\View\MainWindow.xaml.cs:line 78
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)`

Same error appears when clicking folder/browse for Unpack > Select *.pack file to unpack:

paths can be input manually and work when clicking pack, unpack or view content, but then still error when clicking folder/browse.

**Comment by logue** [comment]
This is still an alpha version and a concept release.
This error appears when the output path is not a full path or the file already exists.

Apparently, the registry value can not be read and the location of Mabinogi's directory seems to be in an incomplete state.
The output destination should be `C:\Nexon\Mabinogi\packages\*.pack`, but it is `\packages\*.pack`, which is probably an error.

**Comment by shaggyze** [comment]
yea, i realize this is alpha so bugs/errors are expected, just letting you know so you can improve things.
for NA nexon launcher the default path is now C:\Nexon\Library\mabinogi\appdata\packages\ and for NA steam launcher the path is C:\Program Files (x86)\Steam\steamapps\common\Mabinogi\packages\ and the NA registry path is the same as before HKEY_LOCAL_MACHINE\Software\Nexon\Mabinogi\

![regedit_2019-06-23_00-27-32](https://user-images.githubusercontent.com/6075285/59972995-cadcd000-954d-11e9-832c-0f312febc62a.png)

**Comment by logue** [comment]
Is it HKEY_LOCAL_MACHINE?
Since only HKEY_CURRENT_USER was checked, I made a scan for that one in this commit.

An error has been made to raise an exception due to a defect in the specification of the packing directory or unpacking file or output destination.
The error handling here has not been done yet, but I think that a somewhat clear error message will come out.

**Comment by shaggyze** [comment]
oops, sorry your right is HKEY_CURRENT_USER  as shown in the picture.
checking latest commit now.

**Comment by shaggyze** [comment]
changing these in MabiEnvironment.cs fixed the problem

                    using (RegistryKey regkey = Registry.CurrentUser.OpenSubKey(key, false))
                    {
                        if (regkey != null)
                        {
                            return (string)regkey.GetValue("");
                        }
                    }
                }
                foreach (string key in RegistoryKeys)
                {
                    using (RegistryKey regkey = Registry.CurrentUser.OpenSubKey(key, false))
                    {
                        if (regkey != null)
                        {
                            return (string)regkey.GetValue("");

![MabiPacker_2019-06-23_05-45-57](https://user-images.githubusercontent.com/6075285/59976501-48b6d080-957a-11e9-805c-b4cf1cccdc3a.png)

I guess the NA registry no longer has ExecutablePath, but as far as i remember the path has always been (Default) which is just a blank "" key

![regedit_2019-06-23_05-50-15](https://user-images.githubusercontent.com/6075285/59976547-db576f80-957a-11e9-9c78-3169cd947f8e.png)


also version is now working too, so your doing great!

**Comment by logue** [comment]
Does it mean that it is not HKEY_LOCAL_MACHINE after all?
At least for Japanese clients, the default key does not have a value, so if it can not be read from ExecutablePath or LauncherPath, it will be acquired from there.

**Comment by shaggyze** [comment]
yea, sorry it's HKEY_CURRENT_USER and remove ExecutablePath
